version: "3.9"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rake assets:precompile && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: cineopolis
    restart: always
    volumes:
      - .:/CC
    ports:
      - "3000:3000"