# syntax=docker/dockerfile:1
FROM ruby:3.1.3-alpine
RUN apk add --update --no-cache build-base sqlite-libs sqlite-dev mariadb-dev
WORKDIR /CC
COPY ../../Gemfile /CC/Gemfile
COPY ../../Gemfile.lock /CC/Gemfile.lock
COPY ../.. /CC/
RUN bundle install

CMD ["rake", "test"]